# Chart.yaml
apiVersion: v2
name: aktus-platform
description: Umbrella chart for Aktus AI platform
appVersion: "1.0.16"
version: 1.0.16
type: application
home: https://aktus.ai
sources:
  - https://github.com/aktus-ai/aktus-platform-gcp-marketplace

maintainers:
  - name: Aktus AI Support
    email: support@aktus.ai

dependencies:

  # Databases and Message Queues (Level 1)
  - name: aktus-postgres-service
    version: "1.0.16"
    repository: "file://./charts/postgres"
    tags:
      - infrastructure

  - name: rabbitmq
    version: "1.0.16"
    repository: "file://./charts/rabbitmq"
    tags:
      - infrastructure

  - name: redis
    version: "1.0.16"
    repository: "file://./charts/redis"
    tags:
      - infrastructure

  - name: qdrant
    version: "1.0.16"
    repository: "file://./charts/qdrant"
    condition: enableProductionMode
    tags:
      - infrastructure

  # Core Services (Level 2)
  - name: aktus-database-service
    version: "1.0.16"
    repository: "file://./charts/aktus-db-manager"
    condition: enableProductionMode

  - name: aktus-inference-service
    version: "1.0.16"
    repository: "file://./charts/aktus-inference"
    condition: enableProductionMode

  # Application Services (Level 3)
  - name: aktus-research-service
    version: "1.0.16"
    repository: "file://./charts/aktus-research"
    condition: enableProductionMode

  - name: aktus-multimodal-data-ingestion-service
    version: "1.0.16"
    repository: "file://./charts/aktus-multimodal-data-ingestion"
    condition: enableProductionMode

  - name: aktus-embedding-service
    version: "1.0.16"
    repository: "file://./charts/aktus-embedding"
    condition: enableProductionMode

  - name: aktus-knowledge-assistant-service
    version: "1.0.16"
    repository: "file://./charts/aktus-knowledge-assistant"
    condition: enableProductionMode
