# aktus-multimodal-data-ingestion-service/values.yaml
aktusMdi:
  image: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-multimodal-data-ingestion:v1.0.0
  imagePullPolicy: Always
  serviceAccount: "${RELEASE_NAME}-serviceaccount"
  ports:
    flower: 5555
    ocr: 5315
    layout: 5316
  rabbitmq:
    host: "rabbitmq"
    port: "5672"
    vhost: "/"
    username: "guest"
    password: "guest"
  redis:
    host: "redis"
  modelInference:
    host: "aktus-inference:50051"
  vectorEmbedding:
    host: "aktus-embedding:8080"
  paths:
    docUpload: "/document_upload"
    docProcessing: "/doc_processing"
    extractedData: "/extracted_data"
    models: "/models"
  storage:
    models:
      bucketName: "aktus-platform-models"
      readOnly: true
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    docProcessing:
      bucketName: "aktus-platform-doc-processing"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    extractedData:
      bucketName: "aktus-platform-extracted-data"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    docUpload:
      bucketName: "aktus-platform-doc-upload"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
      ephemeral-storage: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
      ephemeral-storage: "5Gi"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
  config:
    flower:
      unauthenticatedApi: "true"
    chartClassifier:
      modelId: "korazer/chart-test-classify"
      defaultTargetClassIdx: "0"
    docClassifier:
      modelId: "naver-clova-ix/donut-base-finetuned-rvlcdip"
      defaultDevice: "cuda"
    tableTransformer:
      defaultDevice: "detect"
    tableParser:
      defaultDevice: "detect"
    yolo:
      modelPath: "/models/yolo/yolov10x_best.pt"
      defaultDevice: "cuda"