# root/schema.yaml

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "1.0.0"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release of Aktus AI Platform.
  supportUrl: https://support.aktus.ai
  supportDescription: >-
    Aktus AI Platform offers multiple support tiers including Standard (email support with 24-48 hour response time 
    during business hours), Premium (email and phone support with 4-8 hour response), and Enterprise (dedicated 
    support manager with 1-4 hour response time). We provide comprehensive documentation, tutorials, and troubleshooting 
    guides at docs.aktus.ai. For immediate assistance, contact support@aktus.ai or call +1 (555) 123-4567 for 
    Premium and Enterprise customers.
  clusterConstraints:
    resources:
      - replicas: 1-2
        requests:
          cpu: 6000m
          memory: 24Gi
        affinity:
          simpleNodeAffinity:
            type: REQUIRE
            matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: In
                values:
                  - nvidia-tesla-a100

  # Service account configuration
  managedUpdates:
    kalmSupported: false
  images:
    aktus-inference:
      properties:
        aktus-inference-service.aktusInference.image:
          type: FULL
          default: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-inference:1.0.0
    aktus-multimodal-data-ingestion:
      properties:
        aktus-multimodal-data-ingestion-service.aktusMdi.image:
          type: FULL
          default: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/multimodal-data-ingestion:1.0.0
    aktus-research:
      properties:
        aktus-research-service.aktusResearch.image:
          type: FULL
          default: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-research:1.0.0
    aktus-database:
      properties:
        aktus-database-service.aktusDatabase.image:
          type: FULL
    aktus-embedding:
      properties:
        aktus-embedding-service.aktusEmbedding.image:
          type: FULL
          default: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-embedding:1.0.0
  billable:
    enabled: true
    costStructure:
      basePrice:
        name: Per Node
        description: Base price per node per month
        priceInUsd: 200
      additionalItems:
        - name: Inference Compute
          description: Price per hour of inference computation
          priceInUsd: 5.00
          unitOfMeasure: hour
          unitQuantityMultiplier: 0.0002777778 # Converts seconds to hours
          displayQuantityUnit: hour
          displayQuantityBase: 3600 # 1 hour = 3600 seconds
          displayQuantityMultiplier: 0.0002777778 # 1/3600
          stockUnit: second
          stockUnitMultiplier: 1
          stockUnitConverterToDisplayQuantity: 0.0002777778 # 1/3600
          reportingGranularity: DAILY
          metricName: aktus_inference_time_seconds

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  serviceAccount:
    type: string
    title: Service Account
    default: "aktus-ai-platform-sa"
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          GCP service account for the application. Needs permissions to manage secrets, configmaps, PVCs (Role provided) and broader cluster edit permissions (ClusterRole 'edit' provided) for managing application components.
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: view
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["secrets", "configmaps", "persistentvolumeclaims"]
                verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Database configurations
  aktusPostgres.username:
    type: string
    title: PostgreSQL Username
    description: Username for PostgreSQL database
    default: root
  
  aktusPostgres.password:
    type: string
    title: PostgreSQL Password
    description: Password for PostgreSQL database
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: false
        base64: false
  
  aktusPostgres.database:
    type: string
    title: PostgreSQL Database
    description: Name of the PostgreSQL database
    default: root
  
  # Storage configurations
  aktusPostgres.persistence.size:
    type: string
    title: PostgreSQL Storage Size
    description: Size of the PostgreSQL persistent volume
    default: 10Gi
  
  storage.chroma.size:
    type: string
    title: Vector Database Storage Size
    description: Size of the persistent volume for the vector database
    default: 10Gi
  
  # Service configurations
  aktus-inference-service.enabled:
    type: boolean
    title: Enable Inference Service
    description: Enable the model inference service
    default: true
  
  aktus-multimodal-data-ingestion-service.enabled:
    type: boolean
    title: Enable Multimodal Data Ingestion
    description: Enable the multimodal data ingestion service
    default: true
  
  aktus-embedding-service.enabled:
    type: boolean
    title: Enable Embedding Service
    description: Enable the vector embedding service
    default: true
  
  aktus-database-service.enabled:
    type: boolean
    title: Enable Database Service
    description: Enable the database manager service
    default: true
  
  aktus-research-service.enabled:
    type: boolean
    title: Enable Research Service
    description: Enable the research service
    default: true

  # GCS storage bucket configurations
  aktusInference.storage.models.bucketName:
    type: string
    title: Models Storage Bucket
    description: GCS bucket name for storing ML models
    default: aktus-models
  
  aktusInference.storage.docUpload.bucketName:
    type: string
    title: Document Upload Bucket
    description: GCS bucket name for document uploads
    default: aktus-ai-platform-doc-upload
  
  aktusInference.storage.docProcessing.bucketName:
    type: string
    title: Document Processing Bucket
    description: GCS bucket name for document processing
    default: aktus-ai-platform-doc-proc
    
  aktusInference.storage.extractedData.bucketName:
    type: string
    title: Extracted Data Bucket
    description: GCS bucket name for extracted document data
    default: aktus-ai-platform-ext-data

  # Billing Configuration
  billing.enabled:
    type: boolean
    title: Enable Usage-Based Billing
    description: Enable tracking and reporting of usage metrics
    default: true

  billing.reportingSecret:
    type: string
    title: GCP Service Account Key for Billing
    description: Base64-encoded Google Cloud service account key for reporting usage metrics
    default: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYWt0dXMtYWktcGxhdGZvcm0tcHVibGljIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAidGVzdC1rZXktaWQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbnRlc3Qta2V5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tIiwKICAiY2xpZW50X2VtYWlsIjogInRlc3RAYWt0dXMtYWktcGxhdGZvcm0tcHVibGljLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogInRlc3QtaWQiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3Rlc3RAYWt0dXMtYWktcGxhdGZvcm0tcHVibGljLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9"
    x-google-marketplace:
      type: STRING
      
  billing.serviceName:
    type: string
    title: Billing Service Name
    description: Service name for usage tracking
    default: aktus-ai-platform.endpoints.aktus-ai-platform-public.cloud.goog
    
  billing.consumerId:
    type: string
    title: Billing Consumer ID
    description: Consumer ID for usage tracking (must start with 'project:')
    default: project:aktus-ai-platform-public
    pattern: ^project:.*$

  # API keys for external services
  secrets.openaiApiKey:
    type: string
    title: OpenAI API Key
    description: API key for OpenAI services
    default: "dummy-key-for-testing"
    x-google-marketplace:
      type: MASKED_FIELD
      
  secrets.huggingfaceLoginKey:
    type: string
    title: Hugging Face Login Key
    description: Login key for accessing Hugging Face models
    default: "dummy-key-for-testing"
    x-google-marketplace:
      type: MASKED_FIELD

required:
  - name
  - namespace
  - storage.chroma.size
  - aktus-database-service.enabled
  - aktus-research-service.enabled
  - aktus-inference-service.enabled
  - aktus-multimodal-data-ingestion-service.enabled
  - aktus-embedding-service.enabled
  - billing.enabled
  - billing.reportingSecret
  - billing.serviceName
  - billing.consumerId
  - secrets.openaiApiKey
  - secrets.huggingfaceLoginKey
