# charts/aktus-gmp-db-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aktus-database
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.networkSettings.databaseServiceIp }}"
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: aktus-database-service