# charts/rabbitmq/values.yaml
rabbitmq:
  image: docker.io/library/rabbitmq:3.13-management-alpine
  managementPort: 15672
  amqpPort: 5672
  definitions:
    enabled: true
    configMap: rabbitmq-definitions
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
    accessMode: ReadWriteOnce