
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    - {{ .Values.qdrant.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
  storageClassName: {{ .Values.qdrant.persistence.storageClass }}