apiVersion: v1
kind: Service
metadata:
  name: qdrant
spec:
  type: {{ .Values.qdrant.service.type | quote }}
  ports:
    - port: {{ .Values.qdrant.service.port }}
      targetPort: {{ .Values.qdrant.port }}
      protocol: TCP
      name: http
  selector:
    app: qdrant 