aktusResearch:
  image: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-research:1.0.0
  imagePullPolicy: Always
  port: 8080
  service:
    type: LoadBalancer
    port: 8080
    loadBalancerIP: ""
  
  auth:
    username: "guest"
    password: "guest"
  
  uvicorn:
    host: "0.0.0.0"
    port: "8080"
    logLevel: "debug"
    timeoutKeepAlive: "3600"
  
  modelInference:
    address: "aktus-inference:50051"
  
  embeddingService:
    host: "aktus-embedding:8080"
  
  paths:
    docUpload: "/document_upload"
    docImage: "/doc_processing" 
    extractedData: "/extracted_data"
  
  # GCS storage configuration
  storage:
    documentUpload:
      bucketName: "aktus-platform-doc-upload"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    docProcessing:
      bucketName: "aktus-platform-doc-processing"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    extractedData:
      bucketName: "aktus-platform-extracted-data"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
  
  resources:
    requests:
      cpu: "4000m"
      memory: "4Gi"
    limits:
      cpu: "4000m"
      memory: "8Gi"

healthcheck:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 60
  failureThreshold: 20

serviceAccount:
  name: "aktus-ai-platform-sa"