aktusKnowledgeAssistant:
  image: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-knowledge-assistant:v1.0.0
  imagePullPolicy: Always
  port: 80
  service:
    type: LoadBalancer
    port: 8080
    loadBalancerIP: ""
  
  # viteSocketUrl: "ws://aktus-research:8080/chat"
  # viteApiBaseUrl: "http://aktus-database:8080"
  # viteWaitlistFormId: "c989a45ed2991b0cb7455a37ced244f0"
  # viteApiEmbedUrl: "http://aktus-embedding:8080"
  # researchServiceUrl: "http://aktus-research:8080"

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m" 
      memory: "1Gi"

serviceAccount:
  name: "${RELEASE_NAME}-serviceaccount"