# aktus-multimodal-data-ingestion-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-multimodal-data-ingestion
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-multimodal-data-ingestion-service
  template:
    metadata:
      labels:
        app: aktus-multimodal-data-ingestion-service
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/ephemeral-storage-limit: "5Gi"
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: "{{ .Release.Name }}-serviceaccount"
      
      containers:
        - name: aktus-multimodal-data-ingestion-service
          image: {{ .Values.aktusMdi.image }}
          imagePullPolicy: {{ .Values.aktusMdi.imagePullPolicy }}
          stdin: true
          tty: true
          workingDir: /usr/src/app
          ports:
            - containerPort: {{ .Values.aktusMdi.ports.flower }}
              name: flower
            - containerPort: {{ .Values.aktusMdi.ports.ocr }}
              name: ocr
            - containerPort: {{ .Values.aktusMdi.ports.layout }}
              name: layout
          env:
            - name: CELERY_CONCURRENCY
              value: "48"
            - name: OCR_TEMPERATURE
              value: "0.0"
            - name: DB_MANAGER_URL
              value: "http://aktus-database"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-secret
                  key: rabbitmq-password
            - name: RABBITMQ_BROKER_HOST
              value: "{{ .Values.aktusMdi.rabbitmq.host }}:{{ .Values.aktusMdi.rabbitmq.port }}"
            - name: RABBITMQ_VHOST
              value: "{{ .Values.aktusMdi.rabbitmq.vhost }}"
            - name: YOLO_LAYOUT_PARSER_DEFAULT_MODEL_PATH
              value: "{{ .Values.aktusMdi.config.yolo.modelPath }}"
            - name: YOLO_LAYOUT_PARSER_DEFAULT_DEVICE
              value: "{{ .Values.aktusMdi.config.yolo.defaultDevice }}"
            - name: RABBITMQ_MONITOR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBITMQ_MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-secret
                  key: rabbitmq-password
            - name: REDIS_BACKEND_URI
              value: "redis://{{ .Values.aktusMdi.redis.host }}/0"
            - name: VDB_ENDPOINT
              value: "http://{{ .Values.aktusMdi.vectorEmbedding.host }}/vectorindex/embed_data"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aktus-openai-secret
                  key: aktus-openai-key
            - name: DOC_UPLOAD_DIR
              value: "{{ .Values.aktusMdi.paths.docUpload }}"
            - name: DOC_PROCESSING_DIR
              value: "{{ .Values.aktusMdi.paths.docProcessing }}"
            - name: EXTRACTED_DATA_DIR
              value: "{{ .Values.aktusMdi.paths.extractedData }}"
            - name: FLOWER_UNAUTHENTICATED_API
              value: "{{ .Values.aktusMdi.config.flower.unauthenticatedApi }}"
            - name: CHART_CLASSIFIER_DEFAULT_MODEL_ID
              value: "{{ .Values.aktusMdi.config.chartClassifier.modelId }}"
            - name: CHART_CLASSIFIER_DEFAULT_TARGET_CLASS_IDX
              value: "{{ .Values.aktusMdi.config.chartClassifier.defaultTargetClassIdx }}"
            - name: DOC_CLASSIFIER_DEFAULT_MODEL_ID
              value: "{{ .Values.aktusMdi.config.docClassifier.modelId }}"
            - name: DOC_CLASSIFIER_DEFAULT_DEVICE
              value: "{{ .Values.aktusMdi.config.docClassifier.defaultDevice }}"
            - name: TABLE_TRANSFORMER_DEFAULT_DEVICE
              value: "{{ .Values.aktusMdi.config.tableTransformer.defaultDevice }}"
            - name: TABLE_PARSER_DEFAULT_DEVICE
              value: "{{ .Values.aktusMdi.config.tableParser.defaultDevice }}"
            - name: AKTUS_CHAT_SERVER_ADDRESS
              value: "{{ .Values.aktusMdi.modelInference.host }}"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: VDB_GRAPHRAG_INDEXING_ENDPOINT
              value: "http://{{ .Values.aktusMdi.vectorEmbedding.host }}/vectorindex/index_graphrag"
          volumeMounts:
            - name: models-data
              mountPath: {{ .Values.aktusMdi.paths.models }}
            - name: doc-processing
              mountPath: {{ .Values.aktusMdi.paths.docProcessing }}
            - name: extracted-data
              mountPath: {{ .Values.aktusMdi.paths.extractedData }}
            - name: document-upload
              mountPath: {{ .Values.aktusMdi.paths.docUpload }}
          resources:
            {{- toYaml .Values.aktusMdi.resources | nindent 12 }}
      volumes:
        {{- if .Values.global.enableGCSAccess }}
        - name: models-data
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusMdi.storage.models.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.aktusMdi.storage.models.bucketName }}
              mountOptions: "{{ .Values.aktusMdi.storage.models.mountOptions }}"
        - name: doc-processing
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusMdi.storage.docProcessing.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.aktusMdi.storage.docProcessing.bucketName }}
              mountOptions: "{{ .Values.aktusMdi.storage.docProcessing.mountOptions }}"
        - name: extracted-data
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusMdi.storage.extractedData.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.aktusMdi.storage.extractedData.bucketName }}
              mountOptions: "{{ .Values.aktusMdi.storage.extractedData.mountOptions }}"
        - name: document-upload
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusMdi.storage.docUpload.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.aktusMdi.storage.docUpload.bucketName }}
              mountOptions: "{{ .Values.aktusMdi.storage.docUpload.mountOptions }}"
        {{- else }}
        - name: models-data
          emptyDir: {}
        - name: doc-processing
          emptyDir: {}
        - name: extracted-data
          emptyDir: {}
        - name: document-upload
          emptyDir: {}
        {{- end }}