# charts/aktus-postgres-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    -- CreateTable
    CREATE TABLE "User" (
        "id" UUID NOT NULL DEFAULT gen_random_uuid(),
        "email" VARCHAR(255) NOT NULL,
        "password_hash" TEXT NOT NULL,
        "salt" TEXT,
        "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP(3) NOT NULL,

        CONSTRAINT "User_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "Domain" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "description" TEXT,
        "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT "Domain_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "Usecase" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "description" TEXT,
        "embedding_model" TEXT NOT NULL DEFAULT '',
        "chunking_strategy" TEXT NOT NULL DEFAULT 'semantic',
        "metric_type" TEXT NOT NULL DEFAULT 'cosine',
        "index_name" TEXT NOT NULL DEFAULT '',
        "in_progress" BOOLEAN NOT NULL DEFAULT FALSE,
        "graphrag_indexed" BOOLEAN NOT NULL DEFAULT FALSE,
        "file_names" TEXT DEFAULT '',
        "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "domain_id" TEXT NOT NULL,

        CONSTRAINT "Usecase_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "FileSummary" (
        "id" TEXT NOT NULL,
        "file_name" TEXT NOT NULL,
        "summary_title" TEXT NOT NULL,
        "summary_text" TEXT NOT NULL,
        "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "usecase_id" TEXT NOT NULL,

        CONSTRAINT "FileSummary_pkey" PRIMARY KEY ("id")
    );

    -- CreateTaskStatusModel enum type
    DO $$ BEGIN
        CREATE TYPE "TaskStatusModel" AS ENUM ('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'REVOKED');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;

    -- CreateTable
    CREATE TABLE "Batch" (
        "id" UUID NOT NULL DEFAULT gen_random_uuid(),
        "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "total_tasks" INTEGER NOT NULL,
        "usecase_id" TEXT NOT NULL,
        "batch_status" "TaskStatusModel" NOT NULL DEFAULT 'PENDING',
        "stoppage_service_name" TEXT,
        "stoppage_task_result" JSONB,
        "total_graphrag_step_number" INTEGER,
        "current_graphrag_step_number" INTEGER,
        "current_graphrag_workflow_name" TEXT,
        "current_graphrag_workflow_status" "TaskStatusModel" DEFAULT 'PENDING',

        CONSTRAINT "Batch_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "Task" (
        "id" UUID NOT NULL DEFAULT gen_random_uuid(),
        "batch_id" UUID NOT NULL,
        "status" "TaskStatusModel" NOT NULL DEFAULT 'PENDING',
        "date_created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "date_updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "expiration_date" TIMESTAMP(3),
        "result" JSONB,
        "service_name" TEXT,
        "task_metadata" JSONB,

        CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
    );

    -- CreateIndex
    CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

    -- CreateIndex
    CREATE UNIQUE INDEX "Domain_name_key" ON "Domain"("name");

    -- AddForeignKey
    ALTER TABLE "Usecase" ADD CONSTRAINT "Usecase_domain_id_fkey" FOREIGN KEY ("domain_id") REFERENCES "Domain"("id") ON DELETE CASCADE ON UPDATE CASCADE;

    -- AddForeignKey
    ALTER TABLE "FileSummary" ADD CONSTRAINT "FileSummary_usecase_id_fkey" FOREIGN KEY ("usecase_id") REFERENCES "Usecase"("id") ON DELETE CASCADE ON UPDATE CASCADE;

    -- AddForeignKey
    ALTER TABLE "Batch" ADD CONSTRAINT "Batch_usecase_id_fkey" FOREIGN KEY ("usecase_id") REFERENCES "Usecase"("id") ON DELETE CASCADE ON UPDATE CASCADE;

    -- AddForeignKey
    ALTER TABLE "Task" ADD CONSTRAINT "Task_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "Batch"("id") ON DELETE CASCADE ON UPDATE CASCADE;