# charts/aktus-postgres-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    -- CreateTable
    CREATE TABLE "User" (
        "id" UUID NOT NULL DEFAULT gen_random_uuid(),
        "email" VARCHAR(255) NOT NULL,
        "password_hash" TEXT NOT NULL,
        "salt" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL,

        CONSTRAINT "User_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "Domain" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "description" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT "Domain_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "Usecase" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "description" TEXT,
        "embedding_model" TEXT NOT NULL DEFAULT '',
        "chunking_strategy" TEXT NOT NULL DEFAULT 'semantic',
        "metric_type" TEXT NOT NULL DEFAULT 'cosine',
        "indexName" TEXT NOT NULL DEFAULT '',
        "graphrag_indexed" BOOLEAN NOT NULL DEFAULT FALSE,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "domainId" TEXT NOT NULL,

        CONSTRAINT "Usecase_pkey" PRIMARY KEY ("id")
    );

    -- CreateTable
    CREATE TABLE "FileSummary" (
        "id" TEXT NOT NULL,
        "file_name" TEXT NOT NULL,
        "summary_title" TEXT NOT NULL,
        "summary_text" TEXT NOT NULL,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "usecaseId" TEXT NOT NULL,

        CONSTRAINT "FileSummary_pkey" PRIMARY KEY ("id")
    );

    -- CreateTaskStatusModel enum type
    CREATE TYPE "TaskStatusModel" AS ENUM ('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'REVOKED');

    -- CreateTable
    CREATE TABLE "Task" (
        "id" UUID NOT NULL,
        "status" "TaskStatusModel" NOT NULL DEFAULT 'PENDING',
        "date_created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "date_updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "expiration_date" TIMESTAMP(3),
        "result" JSONB,
        "service_name" TEXT,
        "task_metadata" JSONB,

        CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
    );

    -- CreateIndex
    CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

    -- CreateIndex
    CREATE UNIQUE INDEX "Domain_name_key" ON "Domain"("name");

    -- AddForeignKey
    ALTER TABLE "Usecase" ADD CONSTRAINT "Usecase_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "Domain"("id") ON DELETE CASCADE ON UPDATE CASCADE;

    -- AddForeignKey
    ALTER TABLE "FileSummary" ADD CONSTRAINT "FileSummary_usecaseId_fkey" FOREIGN KEY ("usecaseId") REFERENCES "Usecase"("id") ON DELETE CASCADE ON UPDATE CASCADE;