# aktus-embedding-service/values.yaml
aktusEmbedding:
  image: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-embedding:v1.0.0
  imagePullPolicy: Always
  serviceAccount: aktus-ai-platform-sa
  port: 8080
  auth:
    username: "guest"
    password: "guest"
  uvicorn:
    host: "0.0.0.0"
    port: "8080"
    logLevel: "info"
    timeoutKeepalive: "3600"
  mdiService:
    endpoint: "http://aktus-multimodal-data-ingestion:5315"
  dbManager:
    host: "http://aktus-database"
  paths:
    extractedData: "/extracted_data"
    docUpload: "/document_upload"
    docProcessing: "/doc_processing"
    chromaDb: "/chroma"
      
  resources:
    requests:
      cpu: "4000m"
      memory: "8Gi"
      ephemeral-storage: "5Gi"
  
  # GCS storage configuration
  storage:
    extractedData:
      bucketName: "aktus-platform-extracted-data"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    docUpload:
      bucketName: "aktus-platform-doc-upload" 
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
    docProcessing:
      bucketName: "aktus-platform-doc-processing"
      readOnly: false
      mountOptions: "implicit-dirs,file-mode=0666,dir-mode=0777"
      
storage:
  chroma:
    size: "50Gi"
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
      
serviceAccount:
  name: "aktus-ai-platform-sa"