# aktus-embedding-service/values.yaml
aktusEmbedding:
  image: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-embedding:v1.0.0
  imagePullPolicy: Always
  port: 8080
  auth:
    username: "guest"
    password: "guest"
  uvicorn:
    host: "0.0.0.0"
    port: "8080"
    logLevel: "info"
    timeoutKeepalive: "3600"
  mdiService:
    endpoint: "http://aktus-multimodal-data-ingestion:5315"
  dbManager:
    host: "http://aktus-database:8080"
  paths:
    extractedData: "/extracted_data"
    docUpload: "/document_upload"
    docProcessing: "/doc_processing"
    graphragData: "/graphrag_data"
      
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
      ephemeral-storage: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
      ephemeral-storage: "2Gi"
  
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
  
  # GCS storage configuration
  storage:
    extractedData:
      bucketName: "aktus-platform-extracted-data"
      readOnly: false
      mountOptions: "implicit-dirs"
    docUpload:
      bucketName: "aktus-platform-doc-upload" 
      readOnly: false
      mountOptions: "implicit-dirs"
    docProcessing:
      bucketName: "aktus-platform-doc-processing"
      readOnly: false
      mountOptions: "implicit-dirs"
      
storage:
  graphragData:
    size: "50Gi"
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
      
serviceAccount:
  name: "aktus-ai-platform-sa"