# charts/aktus-ai-platform/templates/billing-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-billing
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ubbagent