apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}" 