{{- define "serviceAccountName" -}}
{{- if kindIs "string" .Values.serviceAccount -}}
{{- .Values.serviceAccount -}}
{{- else if .Values.serviceAccount.name -}}
{{- .Values.serviceAccount.name -}}
{{- else -}}
aktus-ai-platform-sa
{{- end -}}
{{- end -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-serviceaccount"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/component: "service-account"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app: "{{ .Release.Name }}"
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccountEmail | default "aktus-mp-test-sa@aktus-ai-platform-public.iam.gserviceaccount.com" }}