apiVersion: v1
kind: ServiceAccount
metadata:
  name: "aktus-service-account"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/component: "service-account"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app: "{{ .Release.Name }}"
  annotations:
    iam.gke.io/gcp-service-account: aktus-mp-test-sa@aktus-ai-platform-public.iam.gserviceaccount.com