{{- if .Values.billing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ubbagent-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  config.yaml: |
    identities:
    - name: gcp
      gcp:
        encodedServiceAccountKey: $reporting_key
    metrics:
    - name: aktus_inference_time_seconds
      type: double
      endpoints:
      - name: servicecontrol
      aggregation:
        bufferSeconds: 60
      monitoredResource: gcp_kubernetes_engine_service
    endpoints:
    - name: servicecontrol
      servicecontrol:
        identity: gcp
        serviceName: $service_name
        consumerId: $consumer_id
    agent:
      reportingInterval: 60s
      onError: retry
      endpointsCache:
        expirationTime: 1m
      endpoint_overrides: {}
{{- end }} 