# charts/aktus-ai-platform/templates/ubbagent-secret.yaml
{{- if .Values.billing.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ubbagent-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
data:
  # Adding default placeholder values for testing
  reporting-key: {{ .Values.billing.reportingSecret | default "e30=" | quote }}
  service-name: {{ .Values.billing.serviceName | default "YWt0dXMtYWktcGxhdGZvcm0=" | quote }}
  consumer-id: {{ .Values.billing.consumerId | default "cHJvamVjdDphamtucy1haTppdU5DWnFQdmN3ejR6aGI=" | quote }}
{{- end }}