{{- $reportingSecret := .Values.billing.reportingSecret -}}
{{- $serviceName := .Values.billing.serviceName -}}
{{- $consumerId := .Values.billing.consumerId -}}
{{- if .Values.billing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ubbagent-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  config.yaml: |-
    identities:
    - name: gcp
      gcp:
        encodedServiceAccountKey: {{ $reportingSecret | quote }}
    metrics:
    - name: aktus_inference_time_seconds
      type: double
      endpoints:
      - name: servicecontrol
      aggregation:
        bufferSeconds: 60
      monitoredResource: gcp_kubernetes_engine_service
    endpoints:
    - name: servicecontrol
      servicecontrol:
        identity: gcp
        serviceName: {{ $serviceName | quote }}
        consumerId: {{ $consumerId | quote }}
    agent:
      reportingInterval: 60s
      onError: retry
      endpointsCache:
        expirationTime: 1m
      endpoint_overrides: {}
{{- end }}