# aktus-db-manager/values.yaml
aktusDatabase:
  image: us-docker.pkg.dev/aktus-ai-platform-public/aktus-platform-marketplace/aktus-db-manager:1.0.3
  imagePullPolicy: Always
  port: 80
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  probes:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
  dbConfig:
    username: root
    password: secret
    host: aktus-postgres
    port: 5432
    dbName: root

serviceAccount:
  name: "aktus-ai-platform-sa"