# charts/rabbitmq/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rabbitmq-config
data:
  rabbitmq.conf: |
    default_user = {{ .Values.rabbitmq.username }}
    default_pass = {{ .Values.rabbitmq.password }}
    management.listener.port = {{ .Values.rabbitmq.managementPort }}
    management.listener.ssl = false
    consumer_timeout = 18000000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rabbitmq-definitions
data:
  definitions.json: |
    {
      "users": [
        {
          "name": "{{ .Values.rabbitmq.username }}",
          "password": "{{ .Values.rabbitmq.password }}",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "{{ .Values.rabbitmq.username }}",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }