# charts/rabbitmq/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: {{ .Values.rabbitmq.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.rabbitmq.managementPort }}
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
              {{- if .Values.rabbitmq.persistence.subPath }}
              subPath: {{ .Values.rabbitmq.persistence.subPath }}
              {{- end }}
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: rabbitmq-definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
          resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1000m"
                memory: "2Gi"
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: rabbitmq-data
          {{- if .Values.rabbitmq.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-rabbitmq-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: rabbitmq-config
          configMap:
            name: {{ .Release.Name }}-rabbitmq-config
        - name: rabbitmq-definitions
          configMap:
            name: {{ .Release.Name }}-rabbitmq-definitions