apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
  labels:
    app: {{ .Release.Name }}-rabbitmq
type: Opaque
stringData:
  rabbitmq-user: {{ .Values.rabbitmq.username | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | quote }} 