# aktus-inference-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-inference
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-inference-service
  template:
    metadata:
      annotations:
        kubernetes.io/gpu-accelerator: "true"
        gke-gcsfuse/volumes: "true"
      labels:
        app: aktus-inference-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      terminationGracePeriodSeconds: 60
      containers:
        - name: aktus-inference-service
          image: "{{ .Values.aktusInference.image }}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: HF_LOGIN_KEY
              valueFrom:
                secretKeyRef:
                  name: aktus-huggingface-secret
                  key: login-key
            - name: MINICPM_BASE_MODEL_PATH
              value: "{{ .Values.aktusInference.modelConfig.minicpm.baseModelPath }}"
            - name: MINICPM_PEFT_MODEL_PATH_FLOWCHART
              value: "{{ .Values.aktusInference.modelConfig.minicpm.peftModelPath }}"
            - name: MINICPM_PEFT_MODEL_PATH_TABLE
              value: "{{ .Values.aktusInference.modelConfig.minicpm.peftModelPath }}"
            - name: MINICPM_PROCESSOR_PATH
              value: "{{ .Values.aktusInference.modelConfig.minicpm.processorPath }}"
            - name: YOLO_LAYOUT_PARSER_DEFAULT_MODEL_PATH
              value: "{{ .Values.aktusInference.modelConfig.yolo.modelPath }}"
            - name: SERVER_URI
              value: {{ .Values.aktusInference.serverConfig.uri | quote }}
            - name: ENABLE_FLASH_ATTENTION
              value: {{ .Values.aktusInference.serverConfig.enableFlashAttention | quote }}
            - name: HF_LOCAL_FILES_ONLY
              value: {{ .Values.aktusInference.serverConfig.hfLocalFilesOnly | quote }}
            - name: DEFAULT_DEVICE
              value: {{ .Values.aktusInference.serverConfig.defaultDevice | quote }}
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: CUDA_VISIBLE_DEVICES
              value: "0,1"
            - name: SERVICE_PORT
              value: "{{ .Values.aktusInference.grpcPort }}"
            {{- if $.Values.global.billing.enabled }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELEASE_NAME
              value: {{ $.Release.Name | quote }}
            {{- end }}
          volumeMounts:
            - name: models-data
              mountPath: "{{ .Values.aktusInference.paths.models }}"
            - name: document-upload
              mountPath: "{{ .Values.aktusInference.paths.docUpload }}"
            - name: doc-processing
              mountPath: "{{ .Values.aktusInference.paths.docProcessing }}"
            {{- if $.Values.global.billing.enabled }}
            - name: billing-helper
              mountPath: /usr/local/lib/python3.8/site-packages/billing_metrics.py
              subPath: billing_metrics.py
            {{- end }}
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
      serviceAccountName: {{ $.Values.global.serviceAccount.name }}
      volumes:
        - name: models-data
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: "{{ .Values.aktusInference.storage.models.bucketName }}"
              mountOptions: "{{ .Values.aktusInference.storage.models.mountOptions }}"
        - name: document-upload
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: "{{ .Values.aktusInference.storage.docUpload.bucketName }}"
              mountOptions: "{{ .Values.aktusInference.storage.docUpload.mountOptions }}"
        - name: doc-processing
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: "{{ .Values.aktusInference.storage.docProcessing.bucketName }}"
              mountOptions: "{{ .Values.aktusInference.storage.docProcessing.mountOptions }}"
        {{- if $.Values.global.billing.enabled }}
        - name: billing-helper
          configMap:
            name: {{ $.Release.Name }}-billing-helper
            defaultMode: 0755
        {{- end }}