# aktus-inference-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-inference
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  replicas: {{ .Values.global.aktusInference.replicas | default 1 }}
  selector:
    matchLabels:
      app: aktus-inference-service
  template:
    metadata:
      annotations:
        kubernetes.io/gpu-accelerator: "true"
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/ephemeral-storage-limit: "5Gi"
      labels:
        app: aktus-inference-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      terminationGracePeriodSeconds: 60
      serviceAccountName: "{{ .Release.Name }}-serviceaccount"
      containers:
        - name: aktus-inference-service
          image: {{ .Values.aktusInference.image }}
          imagePullPolicy: {{ .Values.aktusInference.imagePullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.aktusInference.grpcPort | default 50051 }}
              name: grpc
          env:
            - name: HF_LOGIN_KEY
              valueFrom:
                secretKeyRef:
                  name: aktus-huggingface-secret
                  key: login-key
            - name: MINICPM_BASE_MODEL_PATH
              value: "{{ .Values.aktusInference.modelConfig.minicpm.baseModelPath }}"
            - name: MINICPM_PEFT_MODEL_PATH_FLOWCHART
              value: "{{ .Values.aktusInference.modelConfig.minicpm.peftModelPath }}"
            - name: MINICPM_PEFT_MODEL_PATH_TABLE
              value: "{{ .Values.aktusInference.modelConfig.minicpm.peftModelPath }}"
            - name: MINICPM_PROCESSOR_PATH
              value: "{{ .Values.aktusInference.modelConfig.minicpm.processorPath }}"
            - name: YOLO_LAYOUT_PARSER_DEFAULT_MODEL_PATH
              value: "{{ .Values.aktusInference.modelConfig.yolo.modelPath }}"
            - name: SERVER_URI
              value: {{ .Values.aktusInference.serverConfig.uri | quote }}
            - name: ENABLE_FLASH_ATTENTION
              value: {{ .Values.aktusInference.serverConfig.enableFlashAttention | quote }}
            - name: HF_LOCAL_FILES_ONLY
              value: {{ .Values.aktusInference.serverConfig.hfLocalFilesOnly | quote }}
            - name: DEFAULT_DEVICE
              value: "{{ .Values.aktusInference.serverConfig.defaultDevice }}"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
          volumeMounts:
            - name: models-data
              mountPath: {{ .Values.aktusInference.paths.models }}
            - name: document-upload
              mountPath: {{ .Values.aktusInference.paths.docUpload }}
            - name: doc-processing
              mountPath: {{ .Values.aktusInference.paths.docProcessing }}
            - name: ephemeral
              mountPath: "/tmp"
          resources:
            requests:
              nvidia.com/gpu: "1"
              cpu: "4000m"
              memory: "16Gi"
              ephemeral-storage: "5Gi"
            limits:
              nvidia.com/gpu: "1"
              cpu: "8000m"
              memory: "32Gi"
              ephemeral-storage: "5Gi"
      volumes:
        - name: models-data
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusInference.storage.models.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.global.storageSettings.modelsBucketName }}
              mountOptions: "{{ .Values.aktusInference.storage.models.mountOptions }}"
        - name: document-upload
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusInference.storage.docUpload.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.global.storageSettings.docUploadBucketName }}
              mountOptions: "{{ .Values.aktusInference.storage.docUpload.mountOptions }}"
        - name: doc-processing
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: {{ .Values.aktusInference.storage.docProcessing.readOnly }}
            volumeAttributes:
              bucketName: {{ .Values.global.storageSettings.docProcessingBucketName }}
              mountOptions: "{{ .Values.aktusInference.storage.docProcessing.mountOptions }}"
        - name: ephemeral
          emptyDir:
            sizeLimit: 5Gi