# charts/redis/values.yaml
redis:
  image: redis:7.4-alpine
  port: 6379
  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard-rwo
    accessMode: ReadWriteOnce
    subPath: redis-data