# charts/redis/values.yaml
redis:
  image: docker.io/library/redis:7.2-alpine
  port: 6379
  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard-rwo
    accessMode: ReadWriteOnce
    subPath: redis-data