apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-knowledge-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-knowledge-assistant-service
  template:
    metadata:
      labels:
        app: aktus-knowledge-assistant-service
    spec:
      terminationGracePeriodSeconds: 60
      
      serviceAccountName: "{{ .Release.Name }}-serviceaccount"
      containers:
        - name: aktus-knowledge-assistant-service
          image: "{{ .Values.aktusKnowledgeAssistant.image }}"
          imagePullPolicy: "{{ .Values.aktusKnowledgeAssistant.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.aktusKnowledgeAssistant.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: VITE_SOCKET_URL
              value: "ws://{{ .Values.global.networkSettings.researchServiceIp }}:8080/chat"
            - name: DB_MANAGER_ENDPOINT
              value: "{{ .Values.aktusKnowledgeAssistant.dbManagerEndpoint | default .Values.global.dbManagerEndpoint | default "http://aktus-database:8080" }}"
            - name: VITE_API_BASE_URL
              value: "{{ .Values.aktusKnowledgeAssistant.dbManagerEndpoint | default .Values.global.dbManagerEndpoint | default "http://aktus-database:8080" }}"
            - name: VITE_WAITLIST_FORM_ID
              value: "c989a45ed2991b0cb7455a37ced244f0"
            - name: VITE_LEASE_API_BASE_URL
              value: "http://{{ .Values.global.networkSettings.researchServiceIp }}:8080"
            - name: VITE_API_EMBED_URL
              value: "http://{{ .Values.global.networkSettings.embeddingServiceIp }}:8080"
          resources:
            {{- toYaml .Values.aktusKnowledgeAssistant.resources | nindent 12 }}