apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-knowledge-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-knowledge-assistant-service
  template:
    metadata:
      labels:
        app: aktus-knowledge-assistant-service
    spec:
      terminationGracePeriodSeconds: 60
      
      serviceAccountName: "{{ .Release.Name }}-serviceaccount"
      containers:
        - name: aktus-knowledge-assistant-service
          image: {{ .Values.aktusKnowledgeAssistant.image }}
          imagePullPolicy: {{ .Values.aktusKnowledgeAssistant.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.aktusKnowledgeAssistant.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: VITE_SOCKET_URL
              value: "ws://{{ .Values.global.networkSettings.researchServiceIp }}:8080/chat/copilot"
            - name: VITE_API_BASE_URL
              value: {{ .Values.aktusKnowledgeAssistant.viteApiBaseUrl | quote }}
            - name: VITE_WAITLIST_FORM_ID
              value: {{ .Values.aktusKnowledgeAssistant.viteWaitlistFormId | quote }}
          resources:
            {{- toYaml .Values.aktusKnowledgeAssistant.resources | nindent 12 }}