apiVersion: v1
kind: Service
metadata:
  name: aktus-knowledge-assistant
  labels:
    app: aktus-knowledge-assistant-service
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.networkSettings.knowledgeAssistantIp }}"
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: aktus-knowledge-assistant-service