# aktus-gmp-embedding/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-embedding
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-embedding-service
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: aktus-embedding-service
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: "{{ .Release.Name }}-serviceaccount"
      containers:
        - name: aktus-embedding-service
          image: "{{ .Values.aktusEmbedding.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SUMMARIZATION_NUM_PAGES
              value: "50"
            - name: CHUNKING_CONCURRENCY
              value: "50"
            - name: CHUNKING_BATCH_SIZE
              value: "15"
            - name: EMBEDDING_BATCH_SIZE
              value: "15"
            - name: USERNAME
              value: "{{ .Values.aktusEmbedding.auth.username }}"
            - name: PASSWORD
              value: "{{ .Values.aktusEmbedding.auth.password }}"
            - name: HOST_ADDRESS
              value: "{{ .Values.aktusEmbedding.uvicorn.host }}"
            - name: HOST_PORT
              value: "{{ .Values.aktusEmbedding.uvicorn.port }}"
            - name: UVICORN_LOG_LEVEL
              value: "{{ .Values.aktusEmbedding.uvicorn.logLevel }}"
            - name: UVICORN_TIMEOUT_KEEPALIVE
              value: "{{ .Values.aktusEmbedding.uvicorn.timeoutKeepalive }}"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aktus-openai-secret
                  key: aktus-openai-key
            - name: SERVICE_OCR_ENDPOINT
              value: "{{ .Values.aktusEmbedding.mdiService.endpoint }}"
            - name: EXTRACTED_DATA_DIR
              value: "{{ .Values.aktusEmbedding.paths.extractedData }}"
            - name: DOC_UPLOAD_DIR
              value: "{{ .Values.aktusEmbedding.paths.docUpload }}"
            - name: DB_MANAGER_HOST
              value: "{{ .Values.aktusEmbedding.dbManager.host }}"
            - name: QDRANT_URL
              value: "http://qdrant:6333"
            - name: VECTOR_DB_TYPE
              value: "QDRANT"
            - name: ENV
              value: "dev"
            - name: MONGO_URL
              value: mongodb+srv://
            - name: MONGO_DATABASE_NAME
              value: report-gen-db-dev
            - name: MONGO_COLLECTION_NAME
              value: report_rag
            - name: MONGO_INDEX_NAME
              value: reasoning_platform_index
            - name: MONGO_TEXT_KEY
              value: content
            - name: COMMUNITY_REPORT_GRAPH_PROMPT_PATH
              value: "/app/graph/prompts/community_report_graph.txt"
            - name: EXTRACT_CLAIMS_PROMPT_PATH
              value: "/app/graph/prompts/extract_claims.txt"
            - name: PROJECT_ROOT_PATH
              value: "/graphrag_data"
              
          volumeMounts:
            - name: extracted-data
              mountPath: "{{ .Values.aktusEmbedding.paths.extractedData }}"
            - name: document-upload
              mountPath: "{{ .Values.aktusEmbedding.paths.docUpload }}"
            - name: doc-processing
              mountPath: "{{ .Values.aktusEmbedding.paths.docProcessing }}"
            - name: nomic-dir
              mountPath: /root/.nomic
            - name: ephemeral
              mountPath: "/tmp"
            - name: graphrag-data-pvc
              mountPath: {{ .Values.aktusEmbedding.paths.graphragData }}
          resources:
            {{- if .Values.aktusEmbedding.resources }}
            {{- toYaml .Values.aktusEmbedding.resources | nindent 12 }}
            {{- else }}
            requests:
              cpu: "14000m"
              memory: "60Gi"
              ephemeral-storage: "5Gi"
            limits:
              cpu: "14000m"
              memory: "60Gi"
              ephemeral-storage: "5Gi"
            {{- end }}
      volumes:
        {{- if .Values.global.enableGCSAccess }}
        - name: extracted-data
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: {{ .Values.global.storageSettings.extractedDataBucketName | default "aktus-platform-extracted-data" | quote }}
              mountOptions: "implicit-dirs"
        - name: document-upload
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: {{ .Values.global.storageSettings.docUploadBucketName | default "aktus-platform-doc-upload" | quote }}
              mountOptions: "implicit-dirs"
        - name: doc-processing
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: {{ .Values.global.storageSettings.docProcessingBucketName | default "aktus-platform-doc-processing" | quote }}
              mountOptions: "implicit-dirs"
        {{- else }}
        - name: extracted-data
          emptyDir: {}
        - name: document-upload
          emptyDir: {}
        - name: doc-processing
          emptyDir: {}
        {{- end }}
        - name: nomic-dir
          emptyDir: {}
        - name: ephemeral
          emptyDir:
            sizeLimit: 5Gi
        - name: graphrag-data-pvc
          persistentVolumeClaim:
            claimName: graphrag-data-pvc
            readOnly: false