# aktus-embedding-service/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
spec:
  accessModes:
    - {{ .Values.storage.chroma.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.chroma.size }}
  storageClassName: {{ .Values.storage.chroma.storageClass | default "standard" }}