# aktus-embedding-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aktus-embedding
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.aktusEmbedding.port }}
      targetPort: http
      name: http
  selector:
    app: aktus-embedding-service