# aktus-embedding-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aktus-embedding
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.networkSettings.embeddingServiceIp }}"
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: aktus-embedding-service