apiVersion: v1
kind: Service
metadata:
  name: aktus-research
  labels:
    app: aktus-research-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.networkSettings.researchServiceIp }}"
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aktus-research-service