apiVersion: v1
kind: Service
metadata:
  name: aktus-research
  labels:
    app: aktus-research-service
spec:
  type: {{ .Values.aktusResearch.service.type }}
  ports:
    - port: {{ .Values.aktusResearch.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aktus-research-service